### ISSUE TITLE
Some building components are displayed as squares.

### ISSUE THREAD

**Issue by wenxiao2012** [charliebanks/nms-base-builder#68]
I just started playing NMS recently, and I am learning to use your tools to complete complex buildings. 
After importing json data, I found that many building parts can't display the model, but display a square in position. I read the json text, and found that the metal narrow staircase is F_FLOOR, not C_FLOOR in the plug-in. After I manually modify the json text of the save file, some of the metal building parts can be mapped into models normally.
Is this due to the change of game version or other reasons? How can I update the changes of these names due to version?

**Comment by charliebanks** [comment]
Hey there,

Thanks for using the plugin!

NMS had a patch recently which added about 270+ new building parts, and the
plugin isn't compatible yet. I am working on a fix now, but it might take
some time due to the amount of new things they added. When the plugin
doesn't recognise a new part (F_FLOOR) for example, it will display a cube
instead.

Charlie

**Comment by wenxiao2012** [comment]
Thank you for your prompt reply! I wrote a small python script to complete the conversion of part ID in the clipboard, but I also found that there are many new parts without 3d models, which are not just as simple as changing from "metal wall" to "alloy wall".

Are the 3d models in your plugin exported from the game?
