### ISSUE TITLE
Can I assist or update the building parts to adapt to the latest version?

### ISSUE THREAD

**Issue by wenxiao2012** [charliebanks/nms-base-builder#69]
I noticed that charliebanks mentioned he is adapting to the current NMS version. Considering that more than 300 building components are added in the current version, this should be a very time-consuming task, so is it possible for us to help complete the work? I think the following questions are involved here:

1. how to export the 3d model of building parts in the game, and do I need to do some processing after export?

2. For building parts with join points, can I export the data of join points from the game, and do I need to do further processing?

3. For parts that can join with each other, can the corresponding relationship be exported from the game? (Maybe we can ignoring the join restriction between parts with join points? Personally, I don't think this may be necessary)

4. After the edited base data is re-imported into the game archive, the original normal power cable will be disordered. Is this because some join point parameters of power facilities have changed? Can I fix it myself?

**Comment by charliebanks** [comment]
Hi @wenxiao2012 ,

Thank you for your interest in helping out! You're a little late though because I am about 90% complete with the update for Frontiers.

I'm hoping to get something up within the next few days :)

To answer your questions though, out of your own curiosity

1. There is a blender addon called NMSDK that can be used to export models into Blender. I then do me own modelling to produce a simplified/proxy version of this model.
2. I have my own custom snapping logic that is created separately to the NMS system. So I wouldn't know how to extract that information.
3. See above. And yea, Blender already provides the "freedom-of-movement" so not sure anything else needs to be done there.
4. The update I am working on should fix the incorrect placement of cables. :)

**Comment by wenxiao2012** [comment]
Thank you for your reply! This helped me save a lot of time.
Regarding the second point of my question, does it mean that the join points we use in nms-base-builder may not exactly coincide with the positions we use in the game?
On the third point, I found out when looking at the "resources/snapping_pairs.json" file that when adding a new part with a join point, we also need to define other parts that can be linked to this part. I think this constraint can be omitted. It seems that more freedom of construction can be obtained.
Looking forward to your next version update!
